#!/bin/sh
cd /usr/ports/security/p5-Crypt-Blowfish && make install clean
cd /usr/ports/security/p5-Crypt-Blowfish_PP && make install clean
cd /usr/ports/security/p5-Crypt-CBC && make install clean
cd /usr/ports/security/p5-Crypt-OpenSSL-Random && make install clean
cd /usr/ports/security/p5-Crypt-PasswdMD5 && make install clean
cd /usr/security/p5-Digest-HMAC && make install clean
cd /usr/ports/lang/p5-Error && make install clean
cd /usr/ports/devel/p5-ExtUtils-CChecker && make install clean
cd /usr/ports/net/p5-IO-Socket-INET6 && make install clean
cd /usr/ports/security/p5-IO-Socket-SSL && make install clean
cd /usr/ports/devel/p5-IO-Tty && make install clean
cd /usr/ports/irc/p5-IRC-Utils && make install clean
cd /usr/ports/devel/p5-Locale-gettext && make install clean
cd /usr/ports/dns/p5-Net-DNS && make install clean
cd /usr/ports/net-mgmt/p5-Net-IP && make install clean
cd /usr/ports/mail/p5-Net-SMTP-SSL && make install clean
cd /usr/ports/security/p5-Net-SSLeay && make install clean
cd /usr/ports/devel/p5-Object-Pluggable && make install clean
cd /usr/ports/devel/p5-POE && make install clean
cd /usr/ports/dns/p5-POE-Component-Client-DNS && make install clean
cd /usr/ports/irc/p5-POE-Component-IRC && make install clean
cd /usr/ports/irc/p5-POE-Component-IRC-Plugin-Blowfish && make install clean
cd /usr/ports/security/p5-POE-Component-SSLify && make install clean
cd /usr/ports/devel/p5-POE-Component-Syndicator && make install clean
cd /usr/ports/irc/p5-POE-Filter-IRCD && make install clean
cd /usr/ports/devel/p5-POE-Test-Loops && make install clean
cd /usr/ports/net/p5-Socket-GetAddrInfo && make install clean
cd /usr/ports/net/p5-Socket6 && make install clean
cd /usr/ports/devel/p5-Task-Weaken && make install clean
cd /usr/ports/irc/irssi && make install clean
cd /usr/ports/ports-mgmt/portupgrade && make install clean
cd /usr/ports/irc/irssi-fish && make install clean
cd /usr/ports/sysutils/screen && make install clean
cd /usr/ports/sysutils/most && make install clean
cd /usr/ports/games/cowsay && make install clean
cd /usr/ports/lang/tcl86 && make install clean
cd /usr/ports/misc/figlet && make install clean
cd /usr/ports/sysutils/setquota && make install clean
cd /usr/ports/misc/gnuls && make install clean

